CREATE TABLE `bk_tb_feedback_auto_review_promotion_candidate` (
  `id` varchar(36) NOT NULL,
  `owner` varchar(64) NOT NULL,
  `type` enum('alias','rule','threshold','model','operational_policy') NOT NULL,
  `status` enum('candidate','shadow_validated','approved','rejected','active','rolled_back') NOT NULL,
  `origin` enum('human_divergence','shadow_comparison','metric_regression','alias_suggestion','training_run','manual_adjustment') NOT NULL,
  `candidateVersion` varchar(64) NOT NULL,
  `baseReviewVersion` varchar(64) NOT NULL,
  `evidence` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`evidence`)),
  `expectedImpact` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`expectedImpact`)),
  `knownRisk` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`knownRisk`)),
  `rollbackPlan` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`rollbackPlan`)),
  `createdBy` varchar(64) NOT NULL,
  `approvedBy` varchar(64) DEFAULT NULL,
  `approvedAt` datetime DEFAULT NULL,
  `appliedAt` datetime DEFAULT NULL,
  `rolledBackAt` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `rejectedBy` varchar(64) DEFAULT NULL,
  `appliedBy` varchar(64) DEFAULT NULL,
  `rolledBackBy` varchar(64) DEFAULT NULL,
  `rejectedAt` datetime DEFAULT NULL,
  `rollbackReason` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `IDX_feedback_auto_review_candidate_version` (`owner`,`candidateVersion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci