CREATE TABLE `feedback_bkp` (
  `id` varchar(36) NOT NULL,
  `owner` varchar(64) NOT NULL,
  `originalText` text NOT NULL,
  `predictedIntent` text NOT NULL,
  `correctedIntent` text DEFAULT NULL,
  `predictedAccount` text DEFAULT NULL,
  `correctedAccount` text DEFAULT NULL,
  `predictedOriginAccount` text DEFAULT NULL,
  `correctedOriginAccount` text DEFAULT NULL,
  `predictedDestinyAccount` text DEFAULT NULL,
  `correctedDestinyAccount` text DEFAULT NULL,
  `predictedCategory` text NOT NULL,
  `correctedCategory` text DEFAULT NULL,
  `predictedValue` decimal(18,2) NOT NULL,
  `correctedValue` decimal(18,2) DEFAULT NULL,
  `predictedDate` text NOT NULL,
  `correctedDate` text DEFAULT NULL,
  `status` enum('pending','validated','corrected') NOT NULL DEFAULT 'pending',
  `usedForTraining` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci