{
 "title": "Dash Raizes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pontos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Pontos",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "u766359255_raizes",
       "rawSql": "SELECT TOTAL_PONTOS FROM u766359255_raizes.icnt_vw_total_points LIMIT 50 "
      }
     ]
    },
    {
     "title": "Média por linha",
     "type": "stat",
     "description": "Média de pontos por linha",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "u766359255_raizes",
       "rawSql": "SELECT Media_pontos_por_linha FROM u766359255_raizes.icnt_vw_average_per_line LIMIT 50 "
      }
     ]
    },
    {
     "title": "Total por rimto",
     "type": "piechart",
     "description": "Comparativo entre quantidade de pontos por ritmo",
     "gridPos": { "h": 10, "w": 15, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "u766359255_raizes",
       "rawSql": "SELECT ritmo, TOTAL_PONTOS FROM u766359255_raizes.icnt_vw_total_per_rythm LIMIT 50 "
      }
     ]
    },
    {
     "title": "Pontos c/ Audio",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "u766359255_raizes",
       "rawSql": "SELECT COM_AUDIO FROM u766359255_raizes.icnt_vw_total_with_audio LIMIT 50 "
      }
     ]
    },
    {
     "title": "Pontos s/ Audio",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 5, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "u766359255_raizes",
       "rawSql": "SELECT SEM_AUDIO FROM u766359255_raizes.icnt_vw_total_with_audio LIMIT 50 "
      }
     ]
    },
    {
     "title": "Total por linha",
     "type": "barchart",
     "description": "Ranking com total de pontos por linha em ordem decrescente",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "u766359255_raizes",
       "rawSql": "SELECT linha, TOTAL_PONTOS FROM u766359255_raizes.icnt_vw_total_per_line ORDER BY TOTAL_PONTOS DESC LIMIT 50 "
      }
     ]
    }
   ]
  },
  { "title": "Giras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total giras",
   "type": "stat",
   "description": "Giras anotadas desde 24/08/24.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_raizes",
     "rawSql": "SELECT COUNT(gira) FROM u766359255_raizes.tb_giras LIMIT 50 "
    }
   ]
  },
  {
   "title": "Abertas x Fechadas x Festas",
   "type": "piechart",
   "description": "Comparativo entre giras abertas, fechadas e festas (independente de abertas ou fechadas)",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_raizes",
     "rawSql": "select\r\n  (\r\n    select\r\n      count(id)\r\n    from\r\n      tb_giras\r\n    where\r\n      fechada = 1\r\n  ) as fechadas,\r\n  (\r\n    select\r\n      count(id)\r\n    from\r\n      tb_giras\r\n    where\r\n      fechada = 0\r\n  ) as abertas,\r\n  (\r\n    select\r\n      count(id)\r\n    from\r\n      tb_giras_linhas A\r\n    where\r\n      A.festa = 1\r\n    group by\r\n      A.gira\r\n  ) as festas"
    }
   ]
  },
  {
   "title": "Últimas giras",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "dataset": "u766359255_raizes",
     "rawSql": "SELECT\r\n  A.gira as Gira,\r\n  case\r\n    when A.fechada = 1 then 'Sim'\r\n    else 'Nao'\r\n  end Fechada,\r\n  case\r\n    when B.festa = 1 then 'Sim'\r\n    else 'Nao'\r\n  end Festa,\r\n  \r\n  C.nome as Linha\r\nFROM\r\n  tb_giras A\r\n  join tb_giras_linhas B on A.id = B.gira\r\n  join tb_linhas C on B.linha = C.id\r\nOrder By A.gira DESC"
    }
   ]
  },
  {
   "title": "Total giras",
   "type": "stat",
   "description": "Giras anotadas desde 24/08/24.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_raizes",
     "rawSql": "SELECT COUNT(gira) FROM u766359255_raizes.tb_giras LIMIT 50 "
    }
   ]
  },
  {
   "title": "Giras por linha",
   "type": "barchart",
   "description": "Somatória de vezes em que as linhas e orixás foram saudados em gira",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "u766359255_raizes",
     "rawSql": "select\r\n  B.nome as linha,\r\n  count(A.linha) as giras\r\nfrom\r\n  tb_giras_linhas A\r\n  join tb_linhas B on A.linha = B.id\r\ngroup by\r\n  A.linha\r\nORDER BY giras desc "
    }
   ]
  }
 ]
}