{
 "title": "Controle geral",
 "description": "OKR 1: Entender onde há um maior gasto\nObjective: Identificar e entender as principais categorias de despesas pessoais.\n----------------------------------------------------------------\nKey Results:\n\n1. Rastrear todas as despesas diárias por 3 meses.\n2. Categorizar todas as despesas em pelo menos 5 categorias principais.\n3. Analisar o histórico de despesas para identificar as 3 maiores categorias de gasto.\n4. Reduzir os gastos em pelo menos uma das três maiores categorias em 10% até o final do trimestre.\n5. Criar um relatório mensal detalhado das despesas.\n\n----------------------------------------------------------------\nKPIs:\n\n1. Percentual de despesas rastreadas mensalmente.\n2. Número de categorias de despesas identificadas.\n3. Percentual de redução nos gastos nas categorias principais.\n4. Frequência de análise e relatório de despesas (mensalmente).\n5. Valor total das despesas mensais em comparação com meses anteriores.\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Owner",
    "label": "Usuário",
    "query": "select a.id as __value\n         , a.name as __text\n  from TB_USERS a"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Meses",
   "type": "stat",
   "description": "Total de meses gerenciando os gastos",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "SELECT\r\n  COUNT(DISTINCT DATE_FORMAT(created_at, '%Y-%m')) AS number_of_months\r\nFROM\r\n  TB_TRANSACTIONS A\r\nWHERE A.owner = $Owner "
    }
   ]
  },
  {
   "title": "Gastos por mês",
   "type": "stat",
   "description": "Valor gasto por mê e comparativo com mês anterior",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "SELECT\r\n  sum(A.value) as ammount,\r\n  month(A.date) as month\r\nFROM\r\n  TB_TRANSACTIONS A\r\n  join TB_CATEGORIES B on A.category = B.id\r\nwhere\r\n  B.positive is false\r\n  and B.internal is false\r\n  and A.owner = $Owner\r\nGROUP BY\r\n  month(A.date)"
    }
   ]
  },
  {
   "title": "Últimas transações",
   "type": "table",
   "description": "Últimas 50 transações registradas",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "SELECT\r\n  A.date as data,\r\n  A.description as descricao,\r\n  B.name as categoria,\r\n  CASE\r\n    WHEN B.positive THEN A.value\r\n    ELSE A.value * -1\r\n  END as valor,\r\n  C.name as conta\r\nFROM\r\n  TB_TRANSACTIONS A\r\n  JOIN TB_CATEGORIES B on A.category = B.id\r\n  join TB_ACCOUNTS C on A.account = C.id\r\nWHERE A.owner = $Owner \r\nORDER BY\r\n  A.date DESC\r\nLIMIT\r\n  50"
    }
   ]
  },
  {
   "title": "5º Gasto/Categorias",
   "type": "piechart",
   "description": "Top 5 categorias de gastos",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "SELECT\r\n  SUM(A.value) AS TOTAL,\r\n  B.name\r\nFROM\r\n  TB_TRANSACTIONS A\r\n  JOIN TB_CATEGORIES B ON A.category = B.id\r\nWHERE\r\n  B.positive IS FALSE\r\n  AND B.internal IS FALSE\r\n  AND A.owner = $Owner\r\nGROUP BY\r\n  A.category\r\nORDER BY\r\n  TOTAL DESC\r\nLIMIT\r\n  5"
    }
   ]
  },
  {
   "title": "Transações por mês",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "SELECT\r\n  count(A.id) as transactions,\r\n  month(A.date) as month\r\nFROM\r\n  TB_TRANSACTIONS A\r\n   WHERE A.owner = $Owner \r\nGROUP BY\r\n  month(A.date)"
    }
   ]
  },
  {
   "title": "Categorias registradas",
   "type": "stat",
   "description": "Total de categorias registradas no mês",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "SELECT\r\n  count(A.category) as categories,\r\n  month(A.date) as month\r\nFROM\r\n  TB_TRANSACTIONS A\r\n  join TB_CATEGORIES B on A.category = B.id\r\nwhere\r\n  B.positive is false\r\n  and B.internal is false\r\n  and A.owner = $Owner\r\nGROUP BY\r\n  month(A.date)"
    }
   ]
  },
  {
   "title": "3º Gastos/Mês",
   "type": "barchart",
   "description": "Top 3 maiores gastos por mês",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "WITH\r\n  QuarterlyCategorySpend AS (\r\n    SELECT\r\n      A.category,\r\n      CONCAT(YEAR(A.date), '-', MONTH(A.date)) AS month,\r\n      SUM(A.value) AS total_spent,\r\n      ROW_NUMBER() OVER (\r\n        PARTITION BY\r\n          YEAR(A.date),\r\n          MONTH(A.date)\r\n        ORDER BY\r\n          SUM(A.value) DESC\r\n      ) AS ranking\r\n    FROM\r\n      TB_TRANSACTIONS A\r\n      join TB_CATEGORIES D on A.category = D.id\r\n    where\r\n      D.internal is false\r\n      and D.positive is false\r\n    \tand A.owner = $Owner\r\n    GROUP BY\r\n      A.category,\r\n      YEAR(A.date),\r\n      MONTH(A.date)\r\n  )\r\nSELECT\r\n  B.month,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 1 THEN C.name\r\n    END\r\n  ) AS cat1,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 1 THEN B.total_spent\r\n    END\r\n  ) AS cat_value1,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 2 THEN C.name\r\n    END\r\n  ) AS cat2,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 2 THEN B.total_spent\r\n    END\r\n  ) AS cat_value2,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 3 THEN C.name\r\n    END\r\n  ) AS cat3,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 3 THEN B.total_spent\r\n    END\r\n  ) AS cat_value3\r\nFROM\r\n  QuarterlyCategorySpend B\r\n  join TB_CATEGORIES C on B.category = C.id\r\nWHERE\r\n  B.ranking <= 3\r\nGROUP BY\r\n  B.month\r\nORDER BY\r\n  B.month\r\nLIMIT\r\n  5"
    }
   ]
  },
  {
   "title": "Entradas \\ Saídas por mês",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "select\r\n  monthname(a.date) mes,\r\n  sum(\r\n    case\r\n      when b.positive then a.value\r\n      else 0\r\n    end\r\n  ) entradas,\r\n  sum(\r\n    case\r\n      when b.positive is false then a.value\r\n      else 0\r\n    end\r\n  ) saidas\r\nfrom\r\n  TB_TRANSACTIONS a\r\n  join TB_CATEGORIES b on a.category = b.id\r\nwhere a.owner = $Owner \r\ngroup by\r\n  month(a.date)\r\nlimit\r\n  5"
    }
   ]
  },
  {
   "title": "Saldo atual",
   "type": "table",
   "description": "Apenas contas com saldo diferente de 0",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "rawSql": "select a.name\r\n     , a.ammount\r\n  from TB_ACCOUNTS a\r\n  where a.ammount != 0\r\n    and a.owner = $Owner \r\n  order by a.name asc"
    }
   ]
  },
  {
   "title": "3° gastos com redução",
   "type": "barchart",
   "description": "Top 3 categorias por trimestre com comparativo de redução",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "WITH\r\n  QuarterlyCategorySpend AS (\r\n    SELECT\r\n      A.category,\r\n      CONCAT('T', QUARTER(date), '-', YEAR(date)) AS quarter,\r\n      SUM(value) AS total_spent,\r\n      ROW_NUMBER() OVER (\r\n        PARTITION BY\r\n          YEAR(A.date),\r\n          QUARTER(A.date)\r\n        ORDER BY\r\n          SUM(value) DESC\r\n      ) AS ranking\r\n    FROM\r\n      TB_TRANSACTIONS A\r\n      join TB_CATEGORIES B on A.category = B.id\r\n    where\r\n      B.positive is false\r\n      and B.internal is false\r\n      and A.owner = $Owner\r\n    GROUP BY\r\n      A.category,\r\n      YEAR(A.date),\r\n      QUARTER(A.date)\r\n  ),\r\n  Top3Categories AS (\r\n    SELECT\r\n      quarter,\r\n      category,\r\n      total_spent,\r\n      ranking,\r\n      LAG(total_spent) OVER (\r\n        PARTITION BY\r\n          category\r\n        ORDER BY\r\n          quarter\r\n      ) AS prev_total_spent\r\n    FROM\r\n      QuarterlyCategorySpend\r\n    WHERE\r\n      ranking <= 3\r\n  )\r\nSELECT\r\n  A.quarter as trimestre,\r\n  A.category,\r\n  B.name as categoria,\r\n  A.total_spent as 'Valor gasto',\r\n  A.prev_total_spent as 'Valor gasto anterior',\r\n  CASE\r\n    WHEN A.prev_total_spent IS NOT NULL THEN (\r\n      (A.prev_total_spent - A.total_spent) / A.prev_total_spent\r\n    ) * 100\r\n    ELSE NULL\r\n  END AS 'Percentual de redução'\r\nFROM\r\n  Top3Categories A\r\n  join TB_CATEGORIES B on A.category = B.id\r\nORDER BY\r\n  A.quarter,\r\n  A.ranking;"
    }
   ]
  },
  {
   "title": "3º gastos Trimestre",
   "type": "barchart",
   "description": "Top3 categorias com maior gasto por trimestre",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "targets": [
    {
     "dataset": "u766359255_rod",
     "rawSql": "WITH\r\n  QuarterlyCategorySpend AS (\r\n    SELECT\r\n      A.category,\r\n      CONCAT('T', QUARTER(A.date), '-', YEAR(A.date)) AS quarter,\r\n      SUM(A.value) AS total_spent,\r\n      ROW_NUMBER() OVER (\r\n        PARTITION BY\r\n          YEAR(A.date),\r\n          QUARTER(A.date)\r\n        ORDER BY\r\n          SUM(A.value) DESC\r\n      ) AS ranking\r\n    FROM\r\n      TB_TRANSACTIONS A\r\n      join TB_CATEGORIES D on A.category = D.id\r\n    where\r\n      D.internal is false\r\n      and D.positive is false\r\n      and A.owner = $Owner\r\n    GROUP BY\r\n      A.category,\r\n      YEAR(A.date),\r\n      QUARTER(A.date)\r\n  )\r\nSELECT\r\n  B.quarter,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 1 THEN C.name\r\n    END\r\n  ) AS cat1,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 1 THEN B.total_spent\r\n    END\r\n  ) AS cat_value1,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 2 THEN C.name\r\n    END\r\n  ) AS cat2,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 2 THEN B.total_spent\r\n    END\r\n  ) AS cat_value2,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 3 THEN C.name\r\n    END\r\n  ) AS cat3,\r\n  MAX(\r\n    CASE\r\n      WHEN B.ranking = 3 THEN B.total_spent\r\n    END\r\n  ) AS cat_value3\r\nFROM\r\n  QuarterlyCategorySpend B\r\n  join TB_CATEGORIES C on B.category = C.id\r\nWHERE\r\n  B.ranking <= 3\r\nGROUP BY\r\n  B.quarter\r\nORDER BY\r\n  B.quarter\r\nLIMIT\r\n  4"
    }
   ]
  }
 ]
}