name: "Update readme"

on:
  push:
    branches: ["master"]
jobs:
  UpdateReadme:
    name: Update readme files
    runs-on: ubuntu-latest
    if: github.event.pusher.name != "rodcordeiro"
    steps:
      - name: Shows variables
        shell: bash
        run: |
          echo "GithubActor=${{github.event.pusher.name}}"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update readme/index files
        shell: bash
        run: |
          ./update_readme.sh
      - name: Send index.md
        uses: sinshutu/upload-to-discord@v2.0.0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: Readme.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push updates
        with:
          commit_message: Updating Readme
